# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62c99eaa7d2d36c77a31e5927050f8aaec0bc13b649bee907b59f6557542fdedacaac83492fabc7a6cec184b8ca08fc604e0dbe38ecd8bf90f9d5f58f1ca7bac

test:
  secret_key_base: 669b2a12c85823428eb3b0260ef8fbe26967b0eb93a4240df61a8576ace3b20c6cc7364625235a77b26cb919fc0ce8f8307efbe624ece79c753ce8f4cd77368d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
